#!/bin/bash

if [ `whoami` != "root" ]; then
        echo This script needs to be run as root.
        exit 1
fi

echo you are in this directory:
pwd
fullpath=`pwd`
if [[ $fullpath =~ /var/www/.*/web ]]; then

chown -R git:www-data .
echo 'chown -R www-data:www-data - completed'

chown -R www-data:www-data sites/default/files
echo 'chown -R www-data:www-data files - completed'

chown -R www-data:www-data cache
echo 'echo -R www-data:www-data cache - completed'

chown -R www-data:www-data wp-content/uploads
echo 'chown -R www-data:www-data wp uploads - completed'

cd ..

chmod -R g+w ./
echo 'Make all files writable by group'

echo done!

else
        echo Nothing happens here.
fi
